name: 'Setup Gemini CLI'
description: 'Install Node and Gemini CLI and expose on PATH'

inputs:
  node-version:
    description: 'Node version to install'
    required: false
    default: '20'
  # --- ADDED ---
  # This lets you pin a specific version for stable, reproducible builds
  gemini-version:
    description: 'Gemini CLI version to install (e.g., 0.5.0, latest)'
    required: false
    default: 'latest' # Solves your 404 error by getting the newest version

runs:
  using: 'composite'
  steps:
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install Gemini CLI
      shell: bash
      run: |
        # --- MODIFIED ---
        # Uses the new input to install a specific or latest version
        npm install -g @google/gemini-cli@${{ inputs.gemini-version }}
        echo "$(npm config get prefix)/bin" >> $GITHUB_PATH

    - name: Verify Gemini CLI
      shell: bash
      run: |
        which gemini
        gemini --version
