repos:
  - repo: local
    hooks:
      - id: lintrunner
        name: Run lintrunner
        # CLANGTIDY takes dozens of seconds to run and is therefore skipped
        entry: lintrunner --skip CLANGTIDY -a
        language: system
