// clang-format off
/*
 * SPDX-FileCopyrightText: Copyright (c) 2025-present NVIDIA CORPORATION & AFFILIATES.
 * All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause
 */
// clang-format on

// Internally, CUB uses std::is_pointer, not
// cuda::std::is_pointer, and it fails to compile as nvrtc does not
// have <type_traits>. This doesn't seem to be the case with nvcc. A
// WAR for nvrtc is to provide std::is_pointer as an alias of
// cuda::std::is_pointer.
#ifndef __NVCC__
#include <cuda/std/type_traits>
namespace std {
using cuda::std::is_pointer;
} // namespace std
#endif

#include <cub/block/block_scan.cuh>

namespace nvf {
namespace scan {

// Block state constants following nvFuser conventions from fused_reduction.cu
// Scan Domain - TEMPLATE STATE 0
//   - Participating in the scan operation, has values coming in, scanned values
//   coming out
// Iteration Domain - TEMPLATE STATE 1
//   - Not participating in the scan operation, has values across the dimension
//   after scan
constexpr __device__ bool isScan(int STATE) {
  return STATE == 0;
}

constexpr __device__ bool isIter(int STATE) {
  return STATE == 1;
}

// Binary operations for scan are now implemented as lambdas passed from outside
// following the pattern from genReductionOp in codegen.cpp

// Block-parallel scan using CUB BlockScan
// Following nvFuser dimensional template parameter pattern like TopKOp
//
// Template parameters (7 vs TopKOp's 9 - simplified for scan):
// - BLOCK_DIM_X/Y/Z: Block dimensions
// - BLOCK_STATE_X/Y/Z: Domain states (0=Scan, 1=Iter)
// - DataT: Data type
// - ITEMS_PER_THREAD: Items per thread
// - BlockDimT: Block dimension type
// - ScanOpT: Binary operation lambda type
//
// Usage example (lambda generated by codegen.cpp):
//   auto scan_op = [] (auto x, auto y) { return x + y; };  // For Add
//   blockScan<...>(scan_output, input_data, init_value, scan_op, block_dim);
template <
    int BLOCK_DIM_X,
    int BLOCK_DIM_Y,
    int BLOCK_DIM_Z,
    int BLOCK_STATE_X,
    int BLOCK_STATE_Y,
    int BLOCK_STATE_Z,
    typename DataT,
    int ITEMS_PER_THREAD,
    typename BlockDimT,
    typename ScanOpT>
__device__ void blockScan(
    DataT (&scan_output)[ITEMS_PER_THREAD],
    const DataT (&input_data)[ITEMS_PER_THREAD],
    const DataT& init_value,
    ScanOpT scan_op,
    BlockDimT block_dim) {
  // For now, only support all dimensions participating in scan (state=0)
  // This follows the same constraint as TopKOp implementation
  static_assert(
      (isScan(BLOCK_STATE_X) || BLOCK_DIM_X == 1) &&
          (isScan(BLOCK_STATE_Y) || BLOCK_DIM_Y == 1) &&
          (isScan(BLOCK_STATE_Z) || BLOCK_DIM_Z == 1),
      "For now, active TID dimensions must participate in scan");

  // Create temporary buffer for CUB operations since input_data is const
  typename cub_utils::CudaType<DataT>::type temp_data[ITEMS_PER_THREAD];
  typename cub_utils::CudaType<DataT>::type cuda_init =
      cub_utils::CudaType<DataT>::get(init_value);

  for (int i = 0; i < ITEMS_PER_THREAD; i++) {
    temp_data[i] = cub_utils::CudaType<DataT>::get(input_data[i]);
  }

  // CUB BlockScan setup - with proper multi-dimensional block support
  // CUB BlockScan template parameters are simpler than BlockRadixSort:
  // - Key type, Block dimensions, Items per thread, Algorithm (optional)
  using BlockScan = cub::BlockScan<
      typename cub_utils::CudaType<DataT>::type, // Data type
      BLOCK_DIM_X, // X dimension
      cub::BLOCK_SCAN_RAKING, // Algorithm (default for BlockScan)
      BLOCK_DIM_Y, // Y dimension
      BLOCK_DIM_Z // Z dimension
      >;

  // Allocate shared memory for CUB operations
  __shared__ typename BlockScan::TempStorage temp_storage;

  // Perform inclusive scan using the provided binary operation lambda
  BlockScan(temp_storage).InclusiveScan(temp_data, temp_data, scan_op);

  // Copy results back to nvFuser types
  for (int i = 0; i < ITEMS_PER_THREAD; i++) {
    scan_output[i] = cub_utils::NvFuserType<DataT>::get(temp_data[i]);
  }

  // IMPLEMENTATION NOTE: This implementation performs inclusive scan.
  // The init_value parameter is provided for API compatibility with nvFuser
  // ScanOp but is not used in the current inclusive scan implementation.
  // Future enhancement could support both inclusive and exclusive scans.
}

} // namespace scan
} // namespace nvf
