#!/bin/bash
# TEST_UNIT=DummyExample
TEST_UNIT=SimpleComputeComm

WORKING_DIR="/opt/pytorch/Fuser"
DIRECTORY="${WORKING_DIR}/nsight/profiles/${TEST_UNIT}_$(date '+%Y-%m-%d_%H-%M-%S')"

mkdir -p ${DIRECTORY}


for WAIT_BACKEND_CREATION in "1"
do
    for N_ITERATIONS in "1"
    do
        for USE_STREAMS in "1"
        do
            for C in "10"
            do
                for USE_UCC in "0"
                do
                    for COMPUTE_PYTORCH in "0"
                    do
                        for NBR_BACKENDS in "2"
                        do
                            for TL in "CUDA" # "NCCL" #"UCP"
                            do
                                CMD="nsys profile --cudabacktrace=all --wait="primary" -t cublas,cuda,nvtx,ucx -o ${DIRECTORY}/overlap_${TEST_UNIT}_C=${C}_USE_UCC=${USE_UCC}_TL=${TL}_N_ITERATIONS=${N_ITERATIONS}_USE_STREAMS=${USE_STREAMS}_WAIT_BACKEND_CREATION=${WAIT_BACKEND_CREATION}"_COMPUTE_PYTORCH=${COMPUTE_PYTORCH}_NBR_BACKENDS=${NBR_BACKENDS}
                                CMD="${CMD} mpirun -np 8\
                                    -x NVFUSER_OVERLAP_N_ITERATIONS=${N_ITERATIONS}\
                                    -x NVFUSER_OVERLAP_USE_STREAMS=${USE_STREAMS}\
                                    -x NVFUSER_OVERLAP_C=${C}\
                                    -x NVFUSER_OVERLAP_USE_UCC=${USE_UCC}\
                                    -x NVFUSER_OVERLAP_WAIT_BACKEND_CREATION=${WAIT_BACKEND_CREATION}\
                                    -x NVFUSER_OVERLAP_COMPUTE_PYTORCH=${COMPUTE_PYTORCH}\
                                    -x NVFUSER_OVERLAP_NBR_BACKENDS=${NBR_BACKENDS}\
                                    -x UCC_TL_${TL}_TUNE=inf\
                                    -x UCC_COLL_TRACE=info\
                                    "
                                CMD="${CMD} $BUILD_DIRECTORY/test_multidevice --gtest_filter=OverlapTest.${TEST_UNIT}"
                                echo $CMD
                                $CMD
                            done
                        done
                    done
                done
            done
        done
    done
done
