#!/bin/bash
EXPERIMENT=tl_nccl
DATE=$(date +%Y%m%d-%H%M)
LOG_BASE="/opt/pytorch/Fuser/bench/logs"

export LOGS="${LOG_BASE}/${EXPERIMENT}_${DATE}"

mkdir -p $LOGS
LOG_FILE_INFO="${LOGS}/info"
echo "Writing to $LOG_FILE_INFO" | tee -a $LOG_FILE_INFO

NP=8
BACKEND=UCC
S=*
M=*
K=*
N=*
Streams=*
export GTEST_FILTER="OverlapBenchmark.DummyBenchmark/${BACKEND}_S${S}_M${M}_K${K}_N${N}_Streams${Streams}"
echo "gtest filter: $GTEST_FILTER" | tee -a $LOG_FILE_INFO

MPIFLAGS=" -np $NP"
MPIFLAGS+=" -x UCX_NET_DEVICES=mlx5_0:1"
# MPIFLAGS+=" -x UCC_CL_BASIC_TLS=^sharp,mlx5"
# MPIFLAGS+=" -x UCC_COLL_TRACE=info"
MPIFLAGS+=" -x UCC_CL_BASIC_TLS=nccl"
echo "mpi flags: $MPIFLAGS" | tee -a $LOG_FILE_INFO

TEST_CMD="$BUILD_DIRECTORY/test_multidevice --gtest_filter=${GTEST_FILTER}"
echo "test cmd: $TEST_CMD" | tee -a $LOG_FILE_INFO

CMD="mpirun $MPIFLAGS $TEST_CMD"
echo $CMD | tee -a $LOG_FILE_INFO
$CMD | tee -a $LOG_FILE_INFO

