# SPDX-FileCopyrightText: Copyright (c) 2023-present NVIDIA CORPORATION & AFFILIATES.
# All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause

# A workflow to send CI-related helpful information to PRs
name: pull
on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id}}
  cancel-in-progress: true

run-name: CI status hello ${{ github.event.pull_request.number }} - ${{ github.event.pull_request.head.sha }}
jobs:
  status_hello:
    name: send CI hello status
    runs-on: ubuntu-latest
    permissions:
      statuses: write
    steps:
      - name: Set CI hello status
        run: |
          send_status() {
            curl -L -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.event.pull_request.head.sha }} \
            -d "{ \
              \"state\":\"pending\", \
              \"target_url\":\"https://github.com/NVIDIA/Fuser/wiki/Bot-Commands\", \
              \"description\":\"Use !build or !test to start CI. See wiki.\", \
              \"context\":\"$1\" \
            }"
          }

          send_status "nvfuser-ci/build_image_20"

  commit-sanity-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: reject files larger than 5 MB
        run: |
          max_bytes=$((5 * 1024 * 1024))
          too_large=""

          git fetch origin "${{ github.base_ref }}" --depth=1 || true
          files=$(git diff --name-only --diff-filter=AM "origin/${{ github.base_ref }}")

          for file in $files; do
            if [ -f "$file" ]; then
              size=$(stat -c%s "$file")
              if [ "$size" -gt "$max_bytes" ]; then
                too_large+="$file ($size bytes)\n"
              fi
            fi
          done

          if [ -n "$too_large" ]; then
            echo -e "❌ The following files are over 5MB:\n$too_large"
            exit 1
          else
            echo "✅ No large files detected."
          fi
      - name: Check for files that match .gitignore but are tracked
        run: |
          # List tracked files that should be ignored
          violating_files=$(git ls-files --cached --ignored --exclude-standard)

          if [ -n "$violating_files" ]; then
            echo "❌ The following files are committed but should be ignored by .gitignore:"
            echo "$violating_files"
            echo "Please remove them from version control:"
            echo "  git rm --cached <file>"
            exit 1
          else
            echo "✅ No ignored files are tracked. All good!"
          fi
      # - name: more sanity checks in case needed in the future
